#!/bin/bash

set -e -o pipefail
shopt -s nullglob

source /usr/local/lib/entrypoint.sh

args=()
log "Including endpoint configurations ..."
for i in "${GST_RTSP_CONFIG}/"*.conf
do
	endpoint="$(basename "${i}")"
	endpoint="${endpoint%.*}"
	endpoint="${endpoint,,}"
	log "\t${endpoint}"
	args+=("/${endpoint}" "$(cat "${i}")")
done

exec /usr/local/bin/gst-rtsp-cli -b 0.0.0.0 -p 554 "${args[@]}"

